### ISSUE TITLE
Question about tutorial?

### ISSUE THREAD

**Issue by lawinko** [azeemohd786/UnitySwift-Native#1]
I don't know about your way of intergrating unity into native IOS.Can you brief me a little or any tutorial link? Thank you

**Comment by azeemohd786** [comment]
@lawinko , I have video links for Integration Unity in Native iOS 
If u are using Objective C:- https://www.youtube.com/watch?v=DLkeGz5vCzk&t=1675s
Else with Swift:-Part 1 - https://www.youtube.com/watch?v=rHBoZ1qRaFU&t=656s
Full Video Unity Integration in Native, Swift :- https://www.skillshare.com/r/profile/Azeem-Azeez/7105350
Teachable: - https://swift-kat.teachable.com/p/unity-integration-in-native-ios

**Comment by lawinko** [comment]
Thanks for the information.BTW do you have any idea about multiple game integration? Is it possible?

**Comment by azeemohd786** [comment]
@lawinko mean u have multiple unity game in one build. If files are properly integrated it works in multiple game for native iOS. U can call the game with APIs.

**Comment by lawinko** [comment]
@azeemohd786  I mean different unity projects and different builds. Can?

**Comment by azeemohd786** [comment]
@lawinko If with different builds, the files may overwrite. The other way is to change the unity files name for each unity game builds..
Example :- UnityBuild1- suppose files name imported as Data1,Classes1&Library1
for UnityBuild2- suppose files name imported name be like Data2,Classes2&Library2.
Paths should be given for each build and unity version should be same for all builds.. there is chances of getting success but more complicated..

**Comment by lawinko** [comment]
@azeemohd786  My way is creating a framework which included Game-A and Game-B is already including in the main ios project. Both games can run successfully but if I want to run Game - A and Game - B at the same time, I need to kill the app and reopen again.

**Comment by azeemohd786** [comment]
@lawinko If it works then its fine.
